export { AppShell } from './app-shell'
export { GlobalHeader } from './global-header'
export { AppSidebar } from './app-sidebar'
export { OrganizationSwitcher } from './organization-switcher'
export { DomainSwitcher } from './domain-switcher'
export { AIWorkspace } from './ai-workspace'
